version: "3.7"
services:
  no-ip:
    build:
      context: .
      args:
          ALPINE_VERSION: "latest"
    container_name: no-ip-update-client
    environment:
      USERNAME_FILE: /run/secrets/username
      PASSWORD_FILE: /run/secrets/password
      DOMAINS_FILE:  /run/secrets/domains
      INTERVAL_FILE: /run/secrets/interval
    secrets:
      - username
      - password
      - domains
      - interval
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      timeout: 30s
      interval: 60m
      retries: 10

secrets:
 username:
   file: ./secrets/username.txt
 password:
   file: ./secrets/password.txt
 domains:
   file: ./secrets/domains.txt
 interval:
   file: ./secrets/interval.txt

